### PR TITLE
RHCS 4.0 Branding

### PR DESCRIPTION
**Pull request by a2batic**
Signed-off-by: Kanika Murarka <kmurarka@redhat.com>
Screenshots:-
Login page:
screencapture-localhost-4202-2019-07-11-16_55_14 (1)

Navigation:
Screenshot from 2019-07-11 16-55-43

About:
Screenshot from 2019-07-11 16-55-51

Error page:
screencapture-localhost-4202-2019-07-11-16_56_09

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by julienlim** [comment]
@a2batic 
overall it looks pretty good.
The about modal, some word wrapping that's wierd at the bottom and also I think we're covering up shadowman in a strange way.

**Comment by julienlim** [comment]
@a2batic Do you have updated screenshots or an instance I can take a look at?

**Comment by a2batic** [comment]
@julienlim updated the description with latest screenshots, will provide a setup once we have the builds.

**Comment by julienlim** [comment]
@a2batic 

I just took a look at the instance you shared with me -- some comments:

- Login page - there’s a < underneath the Terms, Policy, etc. section — can we remove this?
- For the navigation, when you’re select the non-Dashboard items, can we get the blue line to be a bit lower so it’s lined up with the bottom of the masthead/banner?
- About modal, any thoughts about bringing it the “2nd” column to the left a bit more so the Ceph Manager value does not wrap?
- For the Error page, can we adjust the content so it's in the middle of the page (vs. top aligned) and maybe make the icon a bit bigger?

Thanks.

**Comment by epuertat** [comment]
Downstream favicon (SVG proposal [didn't work with Chrome](https://caniuse.com/#feat=link-icon-svg)):
image

**Comment by epuertat** [comment]
Also "dashboard" term has been removed from Login page and Login component title is now "Login to your account":

image

**Comment by epuertat** [comment]
Change format for `badge` class to use PF label:

image

image

**Comment by epuertat** [comment]
0 0 0 0_4212_(FullHD)

**Comment by epuertat** [comment]
# Before fixing titles in forms and landing page
before_landing before_pool

# After
after_landing
after_pool

**Comment by epuertat** [comment]
## Before
image

## After
image

**Comment by epuertat** [comment]
Replaced pie chart with donut, using real-time updated center text:

captured (6)

**Comment by epuertat** [comment]
## Latest additions

image

Little step-back to comply with PF4 dashboards.
Back to Overpass font.
Status row aligned with Perf & Capacity rows.
Perf and Capacity rows switched order.
New donut chart: client throughput (replacing textual card).

**Comment by epuertat** [comment]
## Branded Forms
### Before
image

### After
image

**Pull request closed without merging**
